import Colors from './colors'

export const GAMES = [
  {
    id: 'belote',
    name: 'Belote',
    nameAr: 'بلوت',
    description: '4-player strategic card game',
    descriptionAr: 'لعبة ورق استراتيجية شعبية لأربعة لاعبين',
    icon: '🃏',
    maxPlayers: 4,
    isPremium: false,
    color: Colors.mauritanian.traditionalRed,
  },
  {
    id: 'answer-win',
    name: 'Answer & Win',
    nameAr: 'أجب واربح',
    description: 'Trivia challenge game',
    descriptionAr: 'تحدي المعرفة والثقافة العامة',
    icon: '🧠',
    maxPlayers: 1,
    isPremium: false,
    color: Colors.mauritanian.islamicGreen,
  },
  {
    id: 'xo',
    name: 'XO (Tic-Tac-Toe)',
    nameAr: 'إكس-أو',
    description: 'Quick 2-player tic-tac-toe',
    descriptionAr: 'لعبة إكس-أو السريعة للاعبين',
    icon: '⭕',
    maxPlayers: 2,
    isPremium: false,
    color: Colors.mauritanian.lightBlue,
  },
  {
    id: 'al-chara',
    name: 'Al-Chara (The Badge)',
    nameAr: 'الشارة',
    description: 'Traditional Mauritanian shooting game',
    descriptionAr: 'لعبة الرماية الموريتانية الأصيلة',
    icon: '🏹',
    maxPlayers: 2,
    isPremium: false,
    color: Colors.mauritanian.amber,
  },
  {
    id: 'tournike',
    name: 'Tournike (Spinner)',
    nameAr: 'تورنيك',
    description: 'Traditional luck-based wheel game',
    descriptionAr: 'لعبة العجلة والحظ التراثية',
    icon: '🎡',
    maxPlayers: 1,
    isPremium: false,
    color: Colors.mauritanian.hennaRed,
  },
  {
    id: 'carre',
    name: 'Carré (Squares)',
    nameAr: 'كاريه',
    description: 'Strategic square-building game',
    descriptionAr: 'لعبة بناء المربعات الذكية',
    icon: '⬜',
    maxPlayers: 2,
    isPremium: false,
    color: Colors.mauritanian.mauritanianBlue,
  },
  {
    id: 'kroul',
    name: 'Kroul (Stone Game)',
    nameAr: 'كرول',
    description: 'Ancient Mauritanian stone strategy game',
    descriptionAr: 'لعبة الحجارة الموريتانية العريقة',
    icon: '🪨',
    maxPlayers: 2,
    isPremium: false,
    color: Colors.mauritanian.darkSand,
  },
  {
    id: 'zamat',
    name: 'Zamat (Mauritanian Checkers)',
    nameAr: 'ظامت',
    description: 'Traditional Mauritanian checkers. Invite one friend and play head-to-head.',
    descriptionAr: 'ظامت: الداما الموريتانية. يمكنك دعوة صديق واحد واللعب ضده مباشرة.',
    icon: '🔴',
    maxPlayers: 2,
    isPremium: false,
    color: Colors.mauritanian.darkGold,
  },
  {
    id: 'saraha',
    name: 'Saraha (Truth)',
    nameAr: 'صراحة',
    description: 'Party truth questions, pass-and-play',
    descriptionAr: 'لعبة صراحة: أسئلة جريئة للتعارف والمرح',
    icon: '💬',
    maxPlayers: 6,
    isPremium: false,
    color: Colors.mauritanian.skyBlue,
  },
  {
    id: 'seik',
    name: 'As-Seik (Dice Duel)',
    nameAr: 'السيك',
    description: 'Fast dice duel, highest score wins',
    descriptionAr: 'السيك: مبارزة نرد سريعة، الأعلى نقاطاً يفوز',
    icon: '🎲',
    maxPlayers: 2,
    isPremium: false,
    color: Colors.mauritanian.lightGreen,
  },
]

export const getGameById = (id: string) => GAMES.find(game => game.id === id)